import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './providers/nextAuthProvider'
import { getServerSession } from 'next-auth'
import { nextAuthOptions } from './api/auth/[...nextauth]/route'
import { dbConnect } from '@/services/db'
import ToastProvider from '@/components/ToastComponent'
import { cookies } from 'next/headers'
const cookkiesStore = cookies()
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  console.log(cookkiesStore.get('Authorization'))
  console.log(cookkiesStore.get('EmailVerification'))
  await dbConnect()
  const session = await getServerSession(nextAuthOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ToastProvider>{children}</ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
